### ISSUE TITLE
Query about Automation Hub availability for cloud.vmware_ops

### ISSUE THREAD

**Issue by dacarab** [redhat-cop/cloud.vmware_ops#83]
Morning, I noticed this collection pop up in automation hub a couple of months or so ago, and have been trying to build an execution environment containing it referencing the automation hub, but as it has community dependencies that are not present in the hub, I get errors from ansible-builder about failing to resolve dependencies.

I can build an ee if I reference the necessary collections in github, but don't really want to do that as it muddies the waters around whether I'm running a supported config or no for our Ansible Automation Platform support contract with Red Hat. 

So my question is, is this intended to be a supported collection available on automation hub, and I just need to badger Red Hat support to get it working, or is it up there in error?

Cheers

**Comment by mikemorency** [comment]
Hi @dacarab 
You may need to update your `ansible.cfg` to reference both the validated and regular galaxies. For example,
```
## /etc/ansible/ansible.cfg

[galaxy]
server_list = certified,validated,public

[galaxy_server.public]
url=https://galaxy.ansible.com

[galaxy_server.validated]
url=https://console.redhat.com/api/automation-hub/content/validated/
auth_url=........
token=..........

[galaxy_server.certified]
url=https://console.redhat.com/api/automation-hub/content/published/
auth_url=........
token=...........
```
