### ISSUE TITLE
Title incorrect on snapshot_management

### ISSUE THREAD

**Issue by IPvSean** [redhat-cop/cloud.vmware_ops#86]
on the readme here: https://github.com/redhat-cop/cloud.vmware_ops/tree/main/roles/snapshot_management

![image](https://github.com/user-attachments/assets/3eb3824e-04be-4df7-835f-9b43f9d4dba8)

probably copy and paste error from the provision virtual machine readme

**Comment by bardielle** [comment]
@IPvSean thanks for your feedback
I opened a [PR](https://github.com/redhat-cop/cloud.vmware_ops/pull/92) to fix it
